modLoader = "javafml"
loaderVersion = "[45,)"

license = "MIT"
issueTrackerURL = "https://github.com/cschierig/immersive-crafting"
showAsResourcePack = false

[[mods]]
modId = "immersive_crafting"
version = "0.3.3"
displayName = "Immersive Crafting"
logoFile = "assets/immersive_crafting/icon.png"
description = "Library mod adding data-driven in-world crafting."

[[dependencies.immersive_crafting]]
modId = "emi"
mandatory = false
versionRange = "[1.0.19,)"

