# Project
modVersion=0.6.1
modGroup=com.carlschierig.immersivecrafting
modName=Immersive Crafting
modArchiveName=immersivecrafting
modId=immersive_crafting
modDescription=Library mod adding data-driven in-world crafting.
modLicense=MIT
author=CozyPenguin
# Gradle Properties
org.gradle.jvmargs=-Xmx3G
org.gradle.parallel=true
# Mod Properties
recipeViewer=jei
compatMods=true
# Multiloader
withApiJar=true
withSourcesJar=true
withExampleMod=true
# Modrinth
modrinthId=immersive-crafting
# alpha, beta or release
modrinthType=beta
curseforgeId=1564081
