# Project
modVersion=0.5.0
modGroup=com.carlschierig
modName=Immersive Crafting
modArchiveName=immersivecrafting
modId=immersive_crafting
author=Carl Schierig
modDescription=Library mod adding data-driven in-world crafting.
modLicense=MIT
# Gradle Properties
org.gradle.jvmargs=-Xmx3G
org.gradle.parallel=true
# Architectury
enabledPlatforms=fabric,neoforge
# Fabric
fabric.loom.multiProjectOptimisation=false
# Mod Properties
compatMods=true
recipeViewer=emi
# Multiloader
withApiJar=true
withSourcesJar=true
withExampleMod=true
# Modrinth
# alpha, beta or release
modrinthId=immersive-crafting
modrinthType=alpha
