[versions]
minecraft = "1.21"

minotaur = "2.+"
parchment = "2024.05.01"

fabric_loader = "0.15.+"
fabric_api = "0.100.3+1.21"

neoforge_mdk = "21.0.+"

architectury_loom = "1.6-SNAPSHOT"
architectury_plugin = "3.4-SNAPSHOT"
shadow = "8.1.1"

emi = "1.1.7+1.21"
rei = "16.0.729"
jei = "17.3.0.52"

junit = "5.10.+"

[libraries]
minecraft = { module = "com.mojang:minecraft", version.ref = "minecraft" }

fabric_loader = { module = "net.fabricmc:fabric-loader", version.ref = "fabric_loader" }
fabric_loader_junit = { module = "net.fabricmc:fabric-loader-junit", version.ref = "fabric_loader" }
fabric_api = { module = "net.fabricmc.fabric-api:fabric-api", version.ref = "fabric_api" }

neoforge_mdk = { module = "net.neoforged:neoforge", version.ref = "neoforge_mdk" }

junit_jupiter_api = { module = "org.junit.jupiter:junit-jupiter-api", version.ref = "junit" }
junit_jupiter_engine = { module = "org.junit.jupiter:junit-jupiter-engine", version.ref = "junit" }

compat_modmenu_fabric = { module = "com.terraformersmc:modmenu", version = "11.0.1" }

compat_emi_common = { module = "dev.emi:emi-xplat-mojmap", version.ref = "emi" }

compat_rei_fabric = { module = "me.shedaniel:RoughlyEnoughItems-fabric", version.ref = "rei" }
compat_rei_fabric_api = { module = "me.shedaniel:RoughlyEnoughItems-api-fabric", version.ref = "rei" }
compat_rei_fabric_plugin = { module = "me.shedaniel:RoughlyEnoughItems-default-plugin-fabric", version.ref = "rei" }

[plugins]
minotaur = { id = "com.modrinth.minotaur", version.ref = "minotaur" }

architectury_loom = { id = "dev.architectury.loom", version.ref = "architectury_loom" }
architectury_plugin = { id = "architectury-plugin", version.ref = "architectury_plugin" }
shadow = { id = 'com.github.johnrengelman.shadow', version.ref = "shadow" }
