[versions]
minecraft = "26.1.2"
java = "25"

minotaur = "2.+"
curseforgegradle = "1.1.+"

fabric_loader = "0.19.2"
fabric_loom = "1.15.5"
fabric_api = "0.146.1+26.1.2"

neoforge_mdk = "26.1.2.15-beta"
neoforge_moddev = "2.0.141"
neoforge_neoform = "26.1.2-1"

mixin = "0.8.5"
mixinextras = "0.5.3"

jei = "29.6.2.31"

junit = "6.1.0"

[libraries]
minecraft = { module = "com.mojang:minecraft", version.ref = "minecraft" }

fabric_loader = { module = "net.fabricmc:fabric-loader", version.ref = "fabric_loader" }
fabric_loader_junit = { module = "net.fabricmc:fabric-loader-junit", version.ref = "fabric_loader" }
fabric_api = { module = "net.fabricmc.fabric-api:fabric-api", version.ref = "fabric_api" }

mixin = { module = "org.spongepowered:mixin", version.ref = "mixin" }
mixinextras_common = { module = "io.github.llamalad7:mixinextras-common", version.ref = "mixinextras" }

compat_jei_common_api = { module = "mezz.jei:jei-26.1.2-common-api", version.ref = "jei" }
compat_jei_fabric_api = { module = "mezz.jei:jei-26.1.2-fabric-api", version.ref = "jei" }
compat_jei_fabric = { module = "mezz.jei:jei-26.1.2-fabric", version.ref = "jei" }
compat_jei_neoforge_api = { module = "mezz.jei:jei-26.1.2-neoforge-api", version.ref = "jei" }
compat_jei_neoforge = { module = "mezz.jei:jei-26.1.2-neoforge", version.ref = "jei" }

compat_modmenu_fabric = { module = "com.terraformersmc:modmenu", version = "18.0.0-alpha.8" }

[plugins]
minotaur = { id = "com.modrinth.minotaur", version.ref = "minotaur" }
curseforgegradle = { id = "net.darkhax.curseforgegradle", version.ref = "curseforgegradle" }

fabric_loom = { id = "net.fabricmc.fabric-loom", version.ref = "fabric_loom" }

neoforge_moddev = { id = "net.neoforged.moddev", version.ref = "neoforge_moddev" }
