[versions]
fabric_loom = "1.6-SNAPSHOT"
neoforge_gradle = "7.0.+"
neoforge_mdk = "[20.6,)"
minotaur = "2.+"
parchment = "2024.05.01"

minecraft = "1.20.6"
fabric_loader = "0.15.10"

fabric_api = "0.97.8+1.20.6"
mixin = "0.8.5"

emi = "1.1.6+1.20.6"
rei = "15.0.728"
jei = "17.3.0.52"

[libraries]
minecraft = { module = "com.mojang:minecraft", version.ref = "minecraft" }
fabric_loader = { module = "net.fabricmc:fabric-loader", version.ref = "fabric_loader" }

fabric_api = { module = "net.fabricmc.fabric-api:fabric-api", version.ref = "fabric_api" }
mixin = { module = "org.spongepowered:mixin", version.ref = "mixin" }

emi_fabric = { module = "dev.emi:emi-fabric", version.ref = "emi" }
emi_common = { module = "dev.emi:emi-xplat-mojmap", version.ref = "emi" }
rei = { module = "me.shedaniel:RoughlyEnoughItems-fabric", version.ref = "rei" }

[plugins]
fabric_loom = { id = "fabric-loom", version.ref = "fabric_loom" }
neoforge_gradle = { id = "net.neoforged.gradle.userdev", version.ref = "neoforge_gradle" }
minotaur = { id = "com.modrinth.minotaur", version.ref = "minotaur" }

