modLoader = "javafml"
loaderVersion = "[2,)"

license = "${modLicense}"
issueTrackerURL = "https://github.com/cschierig/immersive-crafting"
showAsResourcePack = false

[[mods]]
modId = "${modId}"
version = "${modVersion}"
displayName = "${modName}"
authors = "CozyPenguin"
logoFile = "assets/immersive_crafting/icon.png"
description = "${modDescription}"
